version: "3"
services:
  app:
    container_name: ruby_sandbox_2.6
    build: .
    environment:
      TZ: 'Asia/Tokyo'
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - .:/home
